### ISSUE TITLE
Unable to build applications on Python 3.12.3  Arch Linux x64

### ISSUE THREAD

**Issue by tejpochiraju** [tusharsadhwani/packaged#21]
`packaged` looks very promising - thanks for releasing it! While checking out the instructions, I can't seem to move past the `pip install -r requirements.txt` or `pip install .` build step. I have tried with a single file custom script as well as the provided minesweeper example.  

```
[tej@a1278 packaged]$ packaged ./example/minesweeper
*** Build Failed:
Stdout:

Stderr:

Traceback (most recent call last):
  File "/home/tej/.local/bin/packaged", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/tej/.local/lib/python3.12/site-packages/packaged/cli.py", line 81, in cli
    create_package(
  File "/home/tej/.local/lib/python3.12/site-packages/packaged/__init__.py", line 93, in create_package
    subprocess.run(
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pip install .']' died with <Signals.SIGILL: 4>.
```
I have tried from inside a venv as well as with packaged installed to my user libs. 

```
[tej@a1278 packaged]$ pip show packaged
Name: packaged
Version: 0.5.3
Summary: The easiest way to ship python applications.
Home-page: https://github.com/tusharsadhwani/packaged
Author: Tushar Sadhwani
Author-email: tushar.sadhwani000@gmail.com
License: GPL-2.0-or-later
Location: /home/tej/.local/lib/python3.12/site-packages
Requires: yaspin, yen
Required-by:
```
```
(venv) [tej@a1278 packaged]$ cat /etc/issue
Manjaro Linux \r  (\n) (\l)

(venv) [tej@a1278 packaged]$ uname -a
Linux a1278 6.9.2-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon May 27 03:56:18 UTC 2024 x86_64 GNU/Linux
```

**Comment by tusharsadhwani** [comment]
Thanks for the heads up! I'll look into the problem and get back to you.
